"""Shared sanitization helpers for operator-facing failure surfaces."""

from __future__ import annotations

import json
import re
from typing import Any

from .compat_diagnostics import FetchCategory, FetchDiagnostic, classify_exception, format_operator_safe

SAFE_FAILURE_MESSAGE = "Request failed with a sanitized diagnostic."
SAFE_PIPELINE_FAILURE_MESSAGE = "Pipeline failed with a sanitized diagnostic."

_ALLOWED_DIAGNOSTICS: dict[FetchCategory, tuple[str, str, bool]] = {
    FetchCategory.TIMEOUT: (
        "Request exceeded its deadline.",
        "retry",
        True,
    ),
    FetchCategory.CONNECTION_ERROR: (
        "Could not establish or maintain a network connection to the host.",
        "retry",
        True,
    ),
    FetchCategory.TLS_ERROR: (
        "TLS handshake or certificate validation failed.",
        "do_not_retry",
        False,
    ),
    FetchCategory.HTTP_ERROR: (
        "Upstream returned a 5xx server-side error.",
        "backoff",
        True,
    ),
    FetchCategory.BLOCKED_OR_FORBIDDEN: (
        "Upstream refused the request (auth / forbidden / rate-limit).",
        "do_not_retry",
        False,
    ),
    FetchCategory.PARSE_ERROR: (
        "Response payload could not be parsed.",
        "do_not_retry",
        False,
    ),
    FetchCategory.UNKNOWN_FETCH_ERROR: (
        "Unclassified fetch failure.",
        "do_not_retry",
        False,
    ),
}

_ALLOWED_CATEGORIES = {item.value for item in FetchCategory}
_ALLOWED_DIAGNOSTIC_KEYS = frozenset(
    {"category", "short_reason", "retry_hint", "is_transient"}
)
_OPERATOR_SAFE_RE = re.compile(
    r"^category=(?P<category>[^;]+); "
    r"short_reason=(?P<short_reason>[^;]+); "
    r"retry_hint=(?P<retry_hint>[^;]+); "
    r"is_transient=(?P<is_transient>true|false)$"
)
_WARNING_RE = re.compile(
    r"^(?P<prefix>Failure|Pipeline failed|Pipeline raised|Pipeline step failed|Pipeline timed out after "
    r"(?:\d+(?:\.\d+)?)s during site_search fetch): (?P<diagnostic>.+)$"
)

_SENSITIVE_PATTERNS: tuple[re.Pattern[str], ...] = (
    re.compile(r"\bBearer\s+[A-Za-z0-9._~+/=-]+", re.IGNORECASE),
    re.compile(r"\bsk-[A-Za-z0-9._-]+", re.IGNORECASE),
    re.compile(r"\bfc-[A-Za-z0-9_-]+", re.IGNORECASE),
    re.compile(
        r"\b[A-Za-z0-9_.-]*(?:api[_-]?key|token|secret|password)"
        r"[A-Za-z0-9_.-]*\s*[:=]\s*\S+",
        re.IGNORECASE,
    ),
    re.compile(r"://[^\s/@:]+:[^\s/@]+@", re.IGNORECASE),
    re.compile(r"\b[A-Z][A-Za-z0-9-]+:\s+\S+"),
    re.compile(r"\b[a-z_]+=[A-Za-z0-9._~+/=-]{16,}", re.IGNORECASE),
)



def _contains_sensitive_text(text: str) -> bool:
    return any(pattern.search(text) for pattern in _SENSITIVE_PATTERNS)


def _category_value(category: Any) -> str | None:
    value = getattr(category, "value", category)
    if not isinstance(value, str):
        return None
    return value


def _parse_operator_safe(line: str) -> dict[str, Any] | None:
    match = _OPERATOR_SAFE_RE.fullmatch(line)
    if match is None:
        return None
    category = match.group("category")
    if category not in _ALLOWED_CATEGORIES:
        return None
    expected = _ALLOWED_DIAGNOSTICS[FetchCategory(category)]
    parsed = {
        "category": category,
        "short_reason": match.group("short_reason"),
        "retry_hint": match.group("retry_hint"),
        "is_transient": match.group("is_transient") == "true",
    }
    if (
        parsed["short_reason"] != expected[0]
        or parsed["retry_hint"] != expected[1]
        or parsed["is_transient"] != expected[2]
    ):
        return None
    return parsed


def _is_exact_safe_warning(text: str) -> bool:
    if text == "conversation log write failed":
        return True
    match = _WARNING_RE.fullmatch(text)
    if match is None:
        return False
    return _parse_operator_safe(match.group("diagnostic")) is not None


def safe_failure_message(exc: BaseException, prefix: str = "Failure") -> str:
    """Return a fixed-prefix message backed only by closed-vocabulary diagnostics."""
    diagnostic = classify_exception(exc)
    return f"{prefix}: {format_operator_safe(diagnostic)}"


def safe_pipeline_failure_message(
    diagnostic: FetchDiagnostic | None,
    fallback: str = SAFE_PIPELINE_FAILURE_MESSAGE,
) -> str:
    """Return a pipeline warning without echoing ``pipeline_result["error"]``."""
    if diagnostic is not None:
        return f"Pipeline failed: {format_operator_safe(diagnostic)}"
    return fallback


def sanitize_warning(value: Any) -> str:
    """Preserve only exact safe diagnostic warnings generated by this code."""
    text = str(value)
    if _contains_sensitive_text(text):
        return SAFE_FAILURE_MESSAGE
    if _is_exact_safe_warning(text):
        return text
    return SAFE_FAILURE_MESSAGE


def sanitize_warnings(values: Any) -> list[str]:
    if not isinstance(values, list):
        return []
    return [sanitize_warning(value) for value in values]


def sanitize_fetch_diagnostic(value: Any) -> dict[str, Any] | None:
    """Keep only the exact closed-vocabulary fetch diagnostic shape."""
    if isinstance(value, FetchDiagnostic):
        return value.to_dict()
    if not isinstance(value, dict):
        return None
    if set(value.keys()) != _ALLOWED_DIAGNOSTIC_KEYS:
        return None

    category_value = _category_value(value.get("category"))
    if category_value not in _ALLOWED_CATEGORIES:
        return None

    category = FetchCategory(category_value)
    expected_reason, expected_retry, expected_transient = _ALLOWED_DIAGNOSTICS[category]
    short_reason = value.get("short_reason")
    retry_hint = value.get("retry_hint")
    is_transient = value.get("is_transient")
    if not isinstance(short_reason, str) or short_reason != expected_reason:
        return None
    if not isinstance(retry_hint, str) or retry_hint != expected_retry:
        return None
    if not isinstance(is_transient, bool) or is_transient != expected_transient:
        return None

    sanitized = {
        "category": category_value,
        "short_reason": short_reason,
        "retry_hint": retry_hint,
        "is_transient": is_transient,
    }
    rendered = json.dumps(sanitized, ensure_ascii=False, sort_keys=True)
    if _contains_sensitive_text(rendered):
        return None
    return sanitized
