"""Build a static Cloudflare Pages demo from the existing Buk-gu MVP.

This script produces ``dist/cloudflare-pages/`` containing a fully static,
backend-free demo that mirrors the live Python ``src/web`` demos. It is the
*only* producer of that directory — originals under ``src/web`` are copied
verbatim and never moved, deleted, or restructured.

Deterministic by design: the demo answers are baked from the committed Buk-gu
snapshot fixture (``tests/fixtures/bukgu_gwangju_demo_snapshot.json``) at build
time. No network, no LLM, no Firecrawl, no requests fetch, no live site call.

Output layout (all under ``dist/cloudflare-pages/``):
    index.html            # static landing page linking to the two demos
    admin.html            # admin_demo.html (template copied + shim injected)
    mobile.html           # mobile_demo.html (template copied + shim injected)
    static/               # verbatim copy of src/web/static/
    snapshot-data.js      # baked snapshot used by the shim
    static-api-shim.js    # deterministic client-side replacement for /api/*

The shim re-declares ``fetch`` so the existing UI code keeps calling
``/api/ask`` / ``/api/info`` / ``/api/test`` unchanged, but responses come from
the inlined snapshot. Because the shim is injected immediately after the
``<body>`` open tag (before the page's own <script> tags), the override is in
place before any module calls ``fetch``.

Usage::

    python3 scripts/build_cloudflare_pages.py
"""

from __future__ import annotations

import json
import os
import shutil
import sys

_THIS_DIR = os.path.dirname(os.path.abspath(__file__))
_REPO_ROOT = os.path.abspath(os.path.join(_THIS_DIR, ".."))
_SYS_PATH_SET = False


def _ensure_repo_on_path() -> None:
    global _SYS_PATH_SET
    if not _SYS_PATH_SET:
        sys.path.insert(0, _REPO_ROOT)
        _SYS_PATH_SET = True


# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
WEB_DIR = os.path.join(_REPO_ROOT, "src", "web")
TEMPLATES_DIR = os.path.join(WEB_DIR, "templates")
STATIC_DIR = os.path.join(WEB_DIR, "static")
SNAPSHOT_FIXTURE = os.path.join(
    _REPO_ROOT, "tests", "fixtures", "bukgu_gwangju_demo_snapshot.json"
)
DIST_ROOT = os.path.join(_REPO_ROOT, "dist", "cloudflare-pages")


# ---------------------------------------------------------------------------
# Snapshot / profile resolution (offline, deterministic)
# ---------------------------------------------------------------------------
def load_snapshot() -> dict:
    """Load the committed Buk-gu snapshot fixture verbatim."""
    with open(SNAPSHOT_FIXTURE, "r", encoding="utf-8") as f:
        return json.load(f)


def resolve_site_profile(site_id: str) -> dict | None:
    """Load the site profile offline; return None on any failure."""
    _ensure_repo_on_path()
    try:
        from src.site_profiles import load_profile

        p = load_profile(site_id)
        return {
            "name": p.name,
            "base_url": p.base_url,
            "classification": getattr(p, "classification", None),
            "preferred_fetch_provider": getattr(p, "preferred_fetch_provider", None),
            "important_keywords": list(getattr(p, "important_keywords", []) or []),
            "fallback_strategy": getattr(p, "fallback_strategy", None),
        }
    except Exception:
        return None


def list_all_profiles() -> list[dict]:
    """List all site profiles offline; return [] on any failure."""
    _ensure_repo_on_path()
    try:
        from src.site_profiles import list_profiles

        return list_profiles()
    except Exception:
        return []


# ---------------------------------------------------------------------------
# HTML injection helpers
# ---------------------------------------------------------------------------
BODY_OPEN = "<body>"


def _inject_after_body_open(html: str, snippet: str) -> str:
    """Insert *snippet* immediately after the first ``<body ...>`` tag.

    Inserting before any page <script> lets the shim's fetch override take
    effect before the UI code runs.
    """
    import re

    # Match <body> with any attributes, non-greedy, first occurrence.
    return re.sub(
        r"(<body[^>]*>)",
        lambda m: m.group(1) + "\n" + snippet,
        html,
        count=1,
    )


def build_snapshot_data_js(snapshot: dict, profile: dict | None) -> str:
    """Serialize the baked snapshot + profile into a JS data module."""
    payload = {
        "snapshot": snapshot,
        "profile": profile,
    }
    return (
        "// AUTO-GENERATED by scripts/build_cloudflare_pages.py — do not edit.\n"
        "// Deterministic, build-time snapshot of the Buk-gu demo. No network.\n"
        "window.__BUKGU_SNAPSHOT__ = "
        + json.dumps(payload, ensure_ascii=False)
        + ";\n"
    )


def build_static_api_shim() -> str:
    """Return a client-side shim that replaces the live /api/* endpoints.

    The shim re-declares a deterministic ``fetch`` that answers the three
    endpoints the original UI calls (/api/ask, /api/info, /api/test) from the
    inlined snapshot. This keeps the original template/JS unchanged while
    making the demo fully static and offline.
    """
    return r"""// AUTO-GENERATED by scripts/build_cloudflare_pages.py — do not edit.
// Deterministic, offline replacement for the Python /api/* endpoints.
// Reads window.__BUKGU_SNAPSHOT__ baked at build time. No network calls.
(function () {
  "use strict";
  var DATA = window.__BUKGU_SNAPSHOT__ || { snapshot: null, profile: null };
  var SNAP = DATA.snapshot || {};
  var PROFILE = DATA.profile || null;

  function delay() { return new Promise(function (r) { setTimeout(r, 120); }); }

  function okJson(obj) {
    return new Promise(function (resolve) {
      resolve({
        ok: true,
        status: 200,
        json: function () { return Promise.resolve(obj); }
      });
    });
  }

  function buildAnswerResponse(question) {
    return {
      site_id: SNAP.site_id,
      site_name: SNAP.site_name,
      question: question,
      answer: SNAP.answer || "",
      sources: SNAP.sources || [],
      search_results: SNAP.search_results || [],
      ok: SNAP.ok !== false,
      answer_ok: SNAP.answer_ok !== false,
      answer_status: SNAP.answer_ok !== false ? "answered" : "error",
      provider: SNAP.provider || "mock",
      model: SNAP.model || "",
      snapshot_mode: true,
      fallback_used: false,
      llm_live: false,
      llm_status: "snapshot",
      llm_label: "Snapshot 데모",
      warnings: [],
      route: "site_search",
      should_search_site: true,
      route_confidence: 1.0,
      route_reason: "static snapshot",
      search_query: question,
      answer_mode: "retrieval_answer",
      source_weak: false,
      fetch_diagnostic: null
    };
  }

  function buildInfoResponse() {
    var snap = SNAP || {};
    var homepage = (snap.homepage_map || {}).homepage || {};
    var navLinks = homepage.navigation_links || [];
    return {
      summary: {
        service_name: "AI 홈페이지 파인더",
        site_id: snap.site_id || "bukgu_gwangju",
        site_name: snap.site_name || (PROFILE ? PROFILE.name : "북구청"),
        provider: snap.provider || "mock",
        model: snap.model || "",
        preset: "-",
        recommended_order: "-",
        llm_live: false,
        llm_status: "snapshot",
        llm_label: "Snapshot 데모",
        fetch_provider: PROFILE ? (PROFILE.preferred_fetch_provider || "-") : "-",
        snapshot_path: "tests/fixtures/bukgu_gwangju_demo_snapshot.json"
      },
      profile: PROFILE || {},
      snapshot: {
        loaded: true,
        path: "tests/fixtures/bukgu_gwangju_demo_snapshot.json",
        fetched_at: snap.fetched_at || "-",
        nav_link_count: navLinks.length,
        source_count: (snap.sources || []).length,
        question: snap.question || "-"
      },
      status: { snapshot_mode: true, fallback_used: false },
      profiles: (window.__BUKGU_PROFILES__ || [])
    };
  }

  function buildTestResponse(question) {
    var r = buildAnswerResponse(question);
    // Admin UI expects site_name/sources/search_results keys; reuse answer.
    r.site_name = SNAP.site_name || (PROFILE ? PROFILE.name : "북구청");
    r.preset = "-";
    r.recommended_order = "-";
    return r;
  }

  // Expose the deterministic info used by admin_demo.js (loaded via /api/info).
  window.__BUKGU_PROFILES__ = (window.__BUKGU_PROFILES__ || []);

  // Override fetch BEFORE the UI scripts run (this shim is injected in <body>).
  var _nativeFetch = window.fetch ? window.fetch.bind(window) : null;
  window.fetch = function (input, init) {
    var url = (input && input.url) ? input.url : String(input);
    var method = (init && init.method) || (input && input.method) || "GET";
    var body = (init && init.body) || (input && input.body) || "{}";

    function postPayload() {
      try { return JSON.parse(body) || {}; } catch (e) { return {}; }
    }

    if (url.indexOf("/api/ask") !== -1) {
      return delay().then(function () { return okJson(buildAnswerResponse(postPayload().question || "")); });
    }
    if (url.indexOf("/api/test") !== -1) {
      return delay().then(function () { return okJson(buildTestResponse(postPayload().question || "")); });
    }
    if (url.indexOf("/api/info") !== -1) {
      return delay().then(function () { return okJson(buildInfoResponse()); });
    }
    // Never hit the network in the static build.
    if (_nativeFetch) return _nativeFetch(input, init);
    return Promise.reject(new Error("Static demo: network disabled"));
  };
})();
"""


def build_index_html(profiles: list[dict]) -> str:
    """Build a static landing page linking to the two demos."""
    profile_items = "".join(
        f"<li><code>{p.get('site_id', '-')}</code> — {p.get('name', '-')}</li>"
        for p in profiles
    ) or "<li>북구청 (bukgu_gwangju)</li>"
    return f"""<!DOCTYPE html>
<html lang="ko">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>400 AI 파인더 — 정적 시연 (Cloudflare Pages)</title>
<style>
  :root {{ --bg:#0f172a; --card:#1e293b; --fg:#e2e8f0; --muted:#94a3b8; --accent:#38bdf8; }}
  * {{ box-sizing: border-box; }}
  body {{ margin:0; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; background:var(--bg); color:var(--fg); }}
  .wrap {{ max-width: 760px; margin: 0 auto; padding: 48px 20px; }}
  h1 {{ font-size: 1.8rem; margin: 0 0 8px; }}
  .sub {{ color: var(--muted); margin-bottom: 32px; }}
  .cards {{ display: grid; gap: 16px; grid-template-columns: 1fr 1fr; }}
  .card {{ display:block; background:var(--card); border-radius:14px; padding:22px; text-decoration:none; color:var(--fg); border:1px solid #334155; transition: transform .15s, border-color .15s; }}
  .card:hover {{ transform: translateY(-3px); border-color: var(--accent); }}
  .card h2 {{ margin: 0 0 6px; font-size:1.15rem; }}
  .card p {{ margin:0; color: var(--muted); font-size:.9rem; }}
  .note {{ margin-top: 32px; padding: 16px; background: var(--card); border-radius:12px; font-size:.85rem; color: var(--muted); }}
  ul {{ margin: 8px 0 0; padding-left: 18px; }}
  code {{ color: var(--accent); }}
</style>
</head>
<body>
<div class="wrap">
  <h1>🏛️ 400 AI 파인더 — 정적 시연</h1>
  <div class="sub">북구청 MVP 정적 배포본 · 빌드 시점 스냅샷 기반 · 네트워크 호출 없음</div>
  <div class="cards">
    <a class="card" href="mobile.html">
      <h2>📱 모바일 챗 데모</h2>
      <p>자연어 질문 → 관련 메뉴 안내</p>
    </a>
    <a class="card" href="admin.html">
      <h2>🖥️ 운영자 화면</h2>
      <p>사이트 프로필 · 스냅샷 상태 · 질문 테스트</p>
    </a>
  </div>
  <div class="note">
    이 데모는 빌드 시점에 고정된 북구청 스냅샷(<code>bukgu_gwangju_demo_snapshot.json</code>)에서 생성된
    결정형 정적 시연입니다. 실제 북구청 사이트·LLM·외부 API 호출은 발생하지 않습니다.
    <ul>{profile_items}</ul>
  </div>
</div>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Copy helpers
# ---------------------------------------------------------------------------
def _copy_tree(src: str, dst: str) -> None:
    """Recursively copy *src* into *dst*, ignoring __pycache__."""
    if os.path.isdir(src):
        os.makedirs(dst, exist_ok=True)
        for entry in os.listdir(src):
            if entry == "__pycache__":
                continue
            _copy_tree(os.path.join(src, entry), os.path.join(dst, entry))
    else:
        os.makedirs(os.path.dirname(dst), exist_ok=True)
        shutil.copy2(src, dst)


def _read_file(path: str) -> str:
    with open(path, "r", encoding="utf-8") as f:
        return f.read()


def _write_file(path: str, content: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content)


# ---------------------------------------------------------------------------
# Main build
# ---------------------------------------------------------------------------
def build() -> None:
    # 1. Refresh dist/cloudflare-pages (build-time only output).
    if os.path.isdir(DIST_ROOT):
        shutil.rmtree(DIST_ROOT)
    os.makedirs(DIST_ROOT, exist_ok=True)

    # 2. Copy static assets verbatim (originals never touched).
    _copy_tree(STATIC_DIR, os.path.join(DIST_ROOT, "static"))
    print("[build] copied static assets")

    # 3. Resolve deterministic demo data (offline).
    snapshot = load_snapshot()
    site_id = snapshot.get("site_id", "bukgu_gwangju")
    profile = resolve_site_profile(site_id)
    profiles = list_all_profiles()
    print(f"[build] snapshot site_id={site_id}, profile={'loaded' if profile else 'missing'}")

    # 4. Bake snapshot data + shim.
    snapshot_js = build_snapshot_data_js(snapshot, profile)
    shim_js = build_static_api_shim()
    _write_file(os.path.join(DIST_ROOT, "snapshot-data.js"), snapshot_js)
    _write_file(os.path.join(DIST_ROOT, "static-api-shim.js"), shim_js)
    print("[build] wrote snapshot-data.js + static-api-shim.js")

    # 5. Emit the landing page.
    index_html = build_index_html(profiles)
    _write_file(os.path.join(DIST_ROOT, "index.html"), index_html)
    print("[build] wrote index.html")

    # 6. Copy + adapt the two demo templates (inject shim, keep originals intact).
    mobile_html = _read_file(os.path.join(TEMPLATES_DIR, "mobile_demo.html"))
    admin_html = _read_file(os.path.join(TEMPLATES_DIR, "admin_demo.html"))

    mobile_snippet = (
        '<script src="snapshot-data.js"></script>\n'
        '<script src="static-api-shim.js"></script>'
    )
    admin_snippet = (
        '<script src="snapshot-data.js"></script>\n'
        '<script src="static-api-shim.js"></script>'
    )

    mobile_out = _inject_after_body_open(mobile_html, mobile_snippet)
    admin_out = _inject_after_body_open(admin_html, admin_snippet)

    _write_file(os.path.join(DIST_ROOT, "mobile.html"), mobile_out)
    _write_file(os.path.join(DIST_ROOT, "admin.html"), admin_out)
    print("[build] wrote mobile.html + admin.html (templates copied, shim injected)")

    print(f"[build] done -> {DIST_ROOT}")


if __name__ == "__main__":
    build()
