"""Generate deterministic browser and Function copies of canonical snapshots."""

from __future__ import annotations

import argparse
import copy
import json
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from src.bukgu_official_snapshot import (  # noqa: E402
    SNAPSHOT_ROOT,
    canonical_snapshot_sha256,
    validate_official_snapshot,
)


BROWSER_TARGET = ROOT / "src" / "web" / "static" / "bukgu-official-snapshots.js"
FUNCTION_TARGET = ROOT / "functions" / "api" / "mvp" / "bukgu-official-snapshots.js"


def load_snapshot_payload() -> dict[str, dict]:
    payload: dict[str, dict] = {}
    for path in sorted(SNAPSHOT_ROOT.glob("*.json")):
        snapshot = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(snapshot, dict):
            raise ValueError(f"snapshot root must be an object: {path}")
        validate_official_snapshot(snapshot)
        route_id = snapshot["route_id"]
        if path.stem != route_id:
            raise ValueError(f"snapshot filename must match route_id: {path}")
        if route_id in payload:
            raise ValueError(f"duplicate snapshot route_id: {route_id}")
        generated = copy.deepcopy(snapshot)
        generated["canonical_sha256"] = canonical_snapshot_sha256(snapshot)
        payload[route_id] = generated
    if not payload:
        raise ValueError("no canonical Buk-gu official snapshots found")
    return payload


def _pretty_json(payload: dict[str, dict]) -> str:
    return json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=False)


def render_browser_artifact(payload: dict[str, dict]) -> str:
    return (
        "// AUTO-GENERATED by scripts/generate_bukgu_official_snapshots.py.\n"
        "// Canonical source: data/official_snapshots/bukgu_gwangju/*.json\n"
        "// Do not edit this file directly.\n"
        "(function (root) {\n"
        "  \"use strict\";\n"
        "  root.__BUKGU_OFFICIAL_SNAPSHOTS__ = "
        + _pretty_json(payload)
        + ";\n"
        "})(typeof window !== \"undefined\" ? window : globalThis);\n"
    )


def render_function_artifact(payload: dict[str, dict]) -> str:
    return (
        "// AUTO-GENERATED by scripts/generate_bukgu_official_snapshots.py.\n"
        "// Canonical source: data/official_snapshots/bukgu_gwangju/*.json\n"
        "// Do not edit this file directly.\n"
        "export const BUKGU_OFFICIAL_SNAPSHOTS = Object.freeze("
        + _pretty_json(payload)
        + ");\n"
    )


def expected_artifacts() -> dict[Path, str]:
    payload = load_snapshot_payload()
    return {
        BROWSER_TARGET: render_browser_artifact(payload),
        FUNCTION_TARGET: render_function_artifact(payload),
    }


def check_generated_artifacts() -> list[Path]:
    stale: list[Path] = []
    for path, expected in expected_artifacts().items():
        try:
            actual = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            actual = ""
        if actual != expected:
            stale.append(path)
    return stale


def write_generated_artifacts() -> None:
    for path, content in expected_artifacts().items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8", newline="\n")
        print(f"[official-snapshot] wrote {path.relative_to(ROOT)}")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when committed generated artifacts do not match canonical JSON",
    )
    args = parser.parse_args()
    if args.check:
        stale = check_generated_artifacts()
        if stale:
            for path in stale:
                print(f"[official-snapshot] stale: {path.relative_to(ROOT)}")
            return 1
        print("[official-snapshot] generated artifacts are current")
        return 0
    write_generated_artifacts()
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
